exports.GuildState = {
  UNAPPROVED: 0,
  PENDING_APROVAL: 1,
  APPROVED: 2,
  INITIALIZING_ROLES: 3,
  INITIALIZING_COMMANDS: 4,
  INITIALIZING_CHANNELS: 5,
  INITIALIZING_WEBHOOKS: 6,
  INITIALIZING_EXTRA: 7,
  READY_TO_USE: 8
};